rewrite ^/index\.html$ / permanent;
rewrite ^/about\.html$ /about/ permanent;
rewrite ^/about/ceny\.html$ /about/ceny/ permanent;
rewrite ^/gallery\.html$ /gallery/ permanent;
rewrite ^/gallery/fyuzing\.html$ /gallery/fyuzing/ permanent;
rewrite ^/gallery/okna\.html$ /gallery/okna/ permanent;
rewrite ^/gallery/podarki\.html$ /gallery/podarki/ permanent;
rewrite ^/gallery/dveri\.html$ /gallery/dveri/ permanent;
rewrite ^/gallery/mozaika\.html$ /gallery/mozaika/ permanent;
rewrite ^/gallery/interery\.html$ /gallery/interery/ permanent;
rewrite ^/gallery/peregorodki\.html$ /gallery/peregorodki/ permanent;
rewrite ^/gallery/potolki\.html$ /gallery/potolki/ permanent;
rewrite ^/gallery/svetilniki\.html$ /gallery/svetilniki/ permanent;
rewrite ^/gallery/rospis\.html$ /gallery/rospis/ permanent;
rewrite ^/komanda\.html$ /komanda/ permanent;
rewrite ^/komanda/spec-1\.html$ /komanda/spec-1/ permanent;
rewrite ^/komanda/spec-2\.html$ /komanda/spec-2/ permanent;
rewrite ^/komanda/spec-3\.html$ /komanda/spec-3/ permanent;
rewrite ^/komanda/spec-4\.html$ /komanda/spec-4/ permanent;
rewrite ^/komanda/spec-5\.html$ /komanda/spec-5/ permanent;
rewrite ^/reviews\.html$ /reviews/ permanent;
rewrite ^/reviews/review-1\.html$ /reviews/review-1/ permanent;
rewrite ^/reviews/review-2\.html$ /reviews/review-2/ permanent;
rewrite ^/reviews/review-3\.html$ /reviews/review-3/ permanent;
rewrite ^/news/news-1\.html$ /news/news-1/ permanent;
rewrite ^/news/news-2\.html$ /news/news-2/ permanent;
rewrite ^/news/news-3\.html$ /news/news-3/ permanent;
rewrite ^/price\.html$ /price/ permanent;
rewrite ^/contacts\.html$ /contacts/ permanent;
